function outputText = OutputText4Report(R, textName)
% this method is designed to create a string to be put within the
% structure Output4Reports (public property, see copmments above)

Label = R.ScenarioLabel;
R.Output4Reports = [];

% SCENARIOS
if strcmp(textName,'Scenarios')
    
    outputText.text = strrep(Label.posteriorAllSingleAssetsViews,' At Horizon Shock ',' ');
    R.Output4Reports.outputText = outputText.text;
    
    % ALLOCATIONS
elseif strcmp(textName,'Allocations')
    
    outputText.text = ['Prior AA:   the optimal asset allocation based on the prior probability.                                                                                                            ' ...
        '                                                                                                                                                                                   ' ...
        'Posterior  AA:   the optimal asset allocation based on the posterior  probability (incorporating views or stress scenarios).                                                         ' ...
        '                                                                                                                                                                                   ' ...
        'For scenario analysis the 2 allocations will be the same since in this case weights are given and no optimization takes place.'];
    R.Output4Reports.outputText = outputText.text;
    
    % ALLOCATIONS MODEL PTF
elseif strcmp(textName,'AllocationsMP')
    
    outputText.text = ['(1) Current AA:   the current asset allocation of the portfolio                                                                                                                       ' ...
        '(2) Prior AA:   the optimal asset allocation based on the prior probability.                                                                                                            ' ...
        '(3) Posterior  AA:   the optimal asset allocation based on the posterior  probability (incorporating views or stress scenarios).                                                                                ' ...
        '(3) - (1):   Posterior AA minus Current AA                                                                                                                                          ' ...
        '(3) - (2):   Posterior AA minus Prior AA                                                                                                                                            ' ...
        'For scenario analysis the 2 allocations will be the same since in this case weights are given and no optimization takes place.                                                                                                                                            ' ...
        'Some assets may be excluded from the analysis for various reasons (e.g. lack of historical data, missing curves, etc – see ''Exception'' page). The sum of the absolute values of the Current Portfolio''s positions included in the analysis is reported as ''Included Notional''.'...
        'Current AA weights refer to the original full portfolio, whose notional value (= sum of abs notionals) is ''Total Notional''.                                                                                                                                                      '...
        'Prior AA and PosteriorAA weights refer to the optimal portfolio drawn from an investment universe that does not include the assets showed on  the ''Exception'' page. All the corresponding monetary values (see ''Monetary Allocation'') are computed using the ''Total Notional''.'];
    
    R.Output4Reports.outputText = outputText.text;
    
    % SUMMARY SA
elseif strcmp(textName,'SummarySA')
    
    outputText.text = 'Risk / Return measures are calculated under both the prior distribution and the posterior distribution. The latter incorporates the stress scenario.';
    R.Output4Reports.outputText = outputText.text;
    
    % SUMMARY MP
elseif strcmp(textName,'SummaryMP')
    
    outputText.text = ['PRIOR AA CURRENT PORTFOLIO: measures based on PRIOR PROBABILITY (without stress scenarios) related to the CURRENT PORTFOLIO (no optimization)' ...
        '                                                                                                                                                                                   ' ...
        'POSTERIOR AA CURRENT PORTFOLIO: measures based on POSTERIOR PROBABILITY (incorporing stress scenarios) related to the CURRENT PORTFOLIO (no optimization)' ...
        '                                                                                                                                                                                   ' ...
        'PRIOR AA PORTFOLIO: measures based on PRIOR PROBABILITY (without stress scenarios) related to the OPTIMIZED PORTFOLIO (on prior distribution)' ...
        '                                                                                                                                                                                   ' ...
        'PRIOR AA PORTFOLIO SHOCKED: measures based on POSTERIOR PROBABILITY (incorporing  stress scenarios) related to the OPTIMIZED PORTFOLIO (on prior distribution)' ...
        '                                                                                                                                                                                   ' ...
        'POSTERIOR AA PORTFOLIO: measures based on PRIOR PROBABILITY (without  stress scenarios) related to the OPTIMIZED PORTFOLIO (on posterior distribution)' ...
        '                                                                                                                                                                                   ' ...
        'POSTERIOR AA PORTFOLIO SHOCKED: measures based on POSTERIOR PROBABILITY (incorporing  stress scenarios) related to the OPTIMIZED PORTFOLIO (on posterior distribution)' ...
        '                                                                                                                                                                                   ' ...
        'For non-scenario analysis (e.g. when dealing with a model portfolio), the data published in this report refer to the choice of a specific point on the efficient frontier.                                                                                                              ' ...
        '                                                                                                                                                                                   ' ...
        'This point is selected on the prior based efficient frontier (see PRIOR target Risk and Target return above), then the point having the closest risk coordinate is chosen on the posterior based efficient frontier.                                                                                                                                    ' ...
        '                                                                                                                                                                                   ' ...
        'The Risk Target can be either Volatility or Expected ShortFall, depending on the Optimization Space used.'];
    R.Output4Reports.outputText = outputText.text;
    
    % PROJ RET
elseif strcmp(textName,'ProjRet')
    
    outputText.text = 'Prior and Posterior RETURNS are the projected (to the investment horizon) assets’ returns under the prior and the posterior distribution. The latter incorporates views/scenarios.';
    R.Output4Reports.outputText = outputText.text;
    
    % MEASURE DESCRIPTION
elseif strcmp(textName,'MargVaR')
    
    outputText.text = ['The Marginal VaR for a given asset is calculated as the difference between the VaR of the full portfolio and the VaR of the portfolio that excludes the asset itself (no stressed risk measures).                                                      ' ...
        '                                                                                                                                                                                   ' ...
        'Current Portfolio: portfolio with current weights.                                                                                                                                 ' ...
        '                                                                                                                                                                                   ' ...
        'Prior Portfolio: portfolio with weights optimized on history.                                                                                                                                 ' ...
        '                                                                                                                                                                                   ' ...
        'Posterior Portfolio: portfolio with weights optimized on scenarios.                                                                                                                                 ' ...
        '                                                                                                                                                                                   '];
    R.Output4Reports.outputText = outputText.text;
    
end

outputText = R.Output4Reports.outputText;

end % OutputText4Report
