function PD = SetInvestmentUniverseED(Pathparams,DAA_params)

%Construct PrepareInputData object
PD = PrepareInputData(portfolioName, ...
                                    dashboardPath, ...
                                    inputExcelPath, ...
                                    outputExcelPath, ...
                                    constantMoneyness, ...
                                    constantTimeToExpiry, ...
                                    includeSpacAndDirgen, ...
                                    addIdenticalAssets);
                                
 %Run macros in EquityPTFtoInvestmentUniverse.xlsm    
 PD.activateMacros;
 %Calculate total notional amount, total notional amount with "LOG" sheet
 %assets included and the difference of these two notionals 
 PD.sumNotionalAmounts;
 
end